---
title: "The Impact of Tuition and Financial Aid on Student Retention and Post-Graduation Outcomes"
subtitle: "Proposal"
author: 
  - name: "Ava Lasater"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "This project will analyze data from the U.S. Department of Education’s College Scorecard 
(https://collegescorecard.ed.gov/data/) to explore how institutional and financial factors influence student outcomes 
across U.S. colleges and universities. Specifically, it will investigate the relationship between cost of attendance and 
key outcome metrics such as retention rates and post-graduation earnings. The working hypothesis is that higher tuition 
combined with limited scholarship support is associated with lower student retention due to increased financial strain, 
while institutions with higher tuition may exhibit higher post-graduation earnings due to factors such as institutional 
prestige and resource availability. The financial burden associated with colllege is becoming increasingly heavy for young 
people, and I am very curious to see what the relationship with student outcomes. "
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
```

## Dataset

```{python}
#| label: load-dataset
#| message: false

data = pd.read_csv("Most-Recent-Cohorts-Institution)


```

A brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.

Make sure to load the data and use inline code for some of this information.

This data contains institution-level data files for 1996-97 through 2022-23 containing aggregate data for each institution. Includes information on 
institutional characteristics, enrollment, student aid, costs, and student outcomes. Field of study-level data files for the pooled 
2014-15, 2015-16 award years through the pooled 2018-19, 2019-20 award years containing data at the credential level and 4-digit 
CIP code combination for each institution. Includes information on cumulative debt at graduation and earnings one year after graduation. 

Initialy, this dataset contains 3306 columns, and 6430 rows. Since this file is too large to load directly into Github, I am 
working on solutions. Thus, I do have have robust numbers and have yet to clean and throw columns that I am not interested in. I
will be retaining a lot of columns related to the cost of attendance, demographic information, and outcome metrics which indclude 
salary metric, retention percentages, etc.

I chose this dataset because it allows me to directly link financial inputs (tuition and aid) with student outcomes (retention 
and earnings), helping to uncover whether affordability or institutional prestige has a stronger effect on student success.



## Questions

The two questions you want to answer.

1. How does average cost of attendance aid affects student retention rates at institutions with different tuition levels?

2. Is there a relationship between institutional tuition and post-graduation earnings, and does this differ by institution 
type (public, private nonprofit, for-profit)?

## Analysis plan

-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external 
data to be merged in (if any).

To answer the first question, I will be looking at the average net prices and retention. There are multiple columns for each of these
factors in the dataset. Next, there are several breakdowns concerning the percentage of student working after graduation. I will use this 
data and compare the type of institution and the tuition to see if there is a relationship. 





The raw data was over 100 mb, so I could not upload it to Github for this assignment. (Ignore this for now, Dr. Chen just provided me another
option for working on this.)

I deleted the following columns so that I could upload the dataset: PELL_DEATH_YR2_RT, PELL_COMP_ORIG_YR2_RT, 
PELL_COMP_4YR_TRANS_YR2_RT, PELL_COMP_2YR_TRANS_YR2_RT, PELL_WDRAW_ORIG_YR2_RT, PELL_WDRAW_4YR_TRANS_YR2_RT, PELL_WDRAW_2YR_TRANS_YR2_RT,
PELL_ENRL_ORIG_YR2_RT, PELL_ENRL_4YR_TRANS_YR2_RT, PELL_ENRL_2YR_TRANS_YR2_RT, PELL_UNKN_ORIG_YR2_RT, PELL_UNKN_4YR_TRANS_YR2_RT, 
PELL_UNKN_2YR_TRANS_YR2_RT, NOPELL_DEATH_YR2_RT, NOPELL_COMP_ORIG_YR2_RT, NOPELL_COMP_4YR_TRANS_YR2_RT, NOPELL_COMP_2YR_TRANS_YR2_RT,
NOPELL_WDRAW_ORIG_YR2_RT, NOPELL_WDRAW_4YR_TRANS_YR2_RT, NOPELL_WDRAW_2YR_TRANS_YR2_RT, NOPELL_ENRL_ORIG_YR2_RT, NOPELL_ENRL_4YR_TRANS_YR2_RT,
NOPELL_ENRL_2YR_TRANS_YR2_RT, NOPELL_UNKN_ORIG_YR2_RT, NOPELL_UNKN_4YR_TRANS_YR2_RT, NOPELL_UNKN_2YR_TRANS_YR2_RT, PELL_DEATH_YR3_RT, 
PELL_COMP_ORIG_YR3_RT, PELL_COMP_4YR_TRANS_YR3_RT, PELL_COMP_2YR_TRANS_YR3_RT, PELL_WDRAW_ORIG_YR3_RT, PELL_WDRAW_4YR_TRANS_YR3_RT, 
PELL_WDRAW_2YR_TRANS_YR3_RT, PELL_ENRL_ORIG_YR3_RT, PELL_ENRL_4YR_TRANS_YR3_RT, PELL_ENRL_2YR_TRANS_YR3_RT, PELL_ENRL_2YR_TRANS_YR3_RT,
PELL_UNKN_ORIG_YR3_RT, PELL_UNKN_4YR_TRANS_YR3_RT, PELL_UNKN_4YR_TRANS_YR3_RT, PELL_UNKN_2YR_TRANS_YR3_RT, NOPELL_DEATH_YR3_RT, 
NOPELL_COMP_ORIG_YR3_RT, NOPELL_COMP_4YR_TRANS_YR3_RT, NOPELL_COMP_4YR_TRANS_YR3_RT, NOPELL_COMP_2YR_TRANS_YR3_RT, NOPELL_WDRAW_ORIG_YR3_RT, 
NOPELL_WDRAW_ORIG_YR3_RT, NOPELL_WDRAW_4YR_TRANS_YR3_RT, NOPELL_WDRAW_2YR_TRANS_YR3_RT, NOPELL_ENRL_ORIG_YR3_RT, NOPELL_ENRL_4YR_TRANS_YR3_RT, 
NOPELL_ENRL_2YR_TRANS_YR3_RT, NOPELL_UNKN_ORIG_YR3_RT, NOPELL_UNKN_4YR_TRANS_YR3_RT, NOPELL_UNKN_2YR_TRANS_YR3_RT, PELL_DEATH_YR4_RT, 
PELL_COMP_ORIG_YR4_RT, PELL_COMP_4YR_TRANS_YR4_RT, PELL_COMP_2YR_TRANS_YR4_RT, PELL_COMP_2YR_TRANS_YR4_RT, PELL_WDRAW_ORIG_YR4_RT, 
PELL_WDRAW_4YR_TRANS_YR4_RT, PELL_WDRAW_2YR_TRANS_YR4_RT, PELL_ENRL_ORIG_YR4_RT, PELL_ENRL_4YR_TRANS_YR4_RT, PELL_ENRL_2YR_TRANS_YR4_RT,
PELL_UNKN_ORIG_YR4_RT, PELL_UNKN_4YR_TRANS_YR4_RT, PELL_UNKN_2YR_TRANS_YR4_RT, NOPELL_DEATH_YR4_RT, NOPELL_COMP_ORIG_YR4_RT, 
NOPELL_COMP_4YR_TRANS_YR4_RT, NOPELL_COMP_2YR_TRANS_YR4_RT, NOPELL_WDRAW_ORIG_YR4_RT, NOPELL_WDRAW_4YR_TRANS_YR4_RT, 
NOPELL_WDRAW_2YR_TRANS_YR4_RT, NOPELL_ENRL_ORIG_YR4_RT, NOPELL_ENRL_4YR_TRANS_YR4_RT, NOPELL_ENRL_2YR_TRANS_YR4_RT, NOPELL_UNKN_ORIG_YR4_RT, 
NOPELL_UNKN_4YR_TRANS_YR4_RT, NOPELL_UNKN_2YR_TRANS_YR4_RT, PELL_DEATH_YR6_RT, PELL_COMP_ORIG_YR6_RT, PELL_COMP_4YR_TRANS_YR6_RT, 
PELL_COMP_2YR_TRANS_YR6_RT, PELL_WDRAW_ORIG_YR6_RT, PELL_WDRAW_4YR_TRANS_YR6_RT, PELL_WDRAW_2YR_TRANS_YR6_RT, PELL_ENRL_ORIG_YR6_RT,
PELL_ENRL_4YR_TRANS_YR6_RT, PELL_ENRL_2YR_TRANS_YR6_RT, PELL_UNKN_ORIG_YR6_RT, PELL_UNKN_4YR_TRANS_YR6_RT, PELL_UNKN_2YR_TRANS_YR6_RT, 
NOPELL_DEATH_YR6_RT, NOPELL_DEATH_YR6_RT, NOPELL_COMP_ORIG_YR6_RT, NOPELL_COMP_4YR_TRANS_YR6_RT, NOPELL_COMP_2YR_TRANS_YR6_RT, 
NOPELL_WDRAW_ORIG_YR6_RT, NOPELL_WDRAW_4YR_TRANS_YR6_RT, NOPELL_WDRAW_2YR_TRANS_YR6_RT, NOPELL_ENRL_ORIG_YR6_RT, 
NOPELL_ENRL_4YR_TRANS_YR6_RT, NOPELL_ENRL_2YR_TRANS_YR6_RT, NOPELL_UNKN_ORIG_YR6_RT, NOPELL_UNKN_4YR_TRANS_YR6_RT, 
NOPELL_UNKN_2YR_TRANS_YR6_RT, PELL_DEATH_YR8_RT, PELL_COMP_ORIG_YR8_RT, PELL_COMP_4YR_TRANS_YR8_RT, PELL_COMP_2YR_TRANS_YR8_RT, 
PELL_WDRAW_ORIG_YR8_RT, PELL_WDRAW_4YR_TRANS_YR8_RT, PELL_WDRAW_2YR_TRANS_YR8_RT, PELL_ENRL_ORIG_YR8_RT, PELL_ENRL_4YR_TRANS_YR8_RT,
PELL_ENRL_2YR_TRANS_YR8_RT, PELL_UNKN_ORIG_YR8_RT, PELL_UNKN_4YR_TRANS_YR8_RT, PELL_UNKN_2YR_TRANS_YR8_RT, NOPELL_DEATH_YR8_RT, 
NOPELL_COMP_ORIG_YR8_RT, NOPELL_COMP_4YR_TRANS_YR8_RT, NOPELL_COMP_2YR_TRANS_YR8_RT, NOPELL_WDRAW_ORIG_YR8_RT, 
NOPELL_WDRAW_4YR_TRANS_YR8_RT, NOPELL_WDRAW_2YR_TRANS_YR8_RT, NOPELL_ENRL_ORIG_YR8_RT, NOPELL_ENRL_4YR_TRANS_YR8_RT, 
NOPELL_ENRL_2YR_TRANS_YR8_RT, NOPELL_UNKN_ORIG_YR8_RT, NOPELL_UNKN_4YR_TRANS_YR8_RT, NOPELL_UNKN_2YR_TRANS_YR8_RT, OMENRYP_NOPELL_ALL,
OMENRAP_NOPELL_ALL, OMAWDP8_NOPELL_ALL, OMENRUP_NOPELL_ALL, OMENRYP_NOPELL_FIRSTTIME, OMENRAP_NOPELL_FIRSTTIME, OMAWDP8_NOPELL_FIRSTTIME, 
OMENRUP_NOPELL_FIRSTTIME, OMENRYP_NOPELL_NOTFIRSTTIME, OMENRAP_NOPELL_NOTFIRSTTIME, OMAWDP8_NOPELL_NOTFIRSTTIME, OMENRUP_NOPELL_NOTFIRSTTIME, 
OMACHT8_NOPELL_ALL, OMACHT8_NOPELL_FIRSTTIME, OMACHT8_NOPELL_NOTFIRSTTIME, BBRR4_PP_NOPELL_DISCHARGE, BBRR4_PP_NOPELL_PAIDINFULL, 
BBRR4_PP_NOPELL_MAKEPROG, BBRR4_PP_NOPELL_NOPROG, BBRR4_PP_NOPELL_DFR, BBRR4_PP_NOPELL_FBR, BBRR4_PP_NOPELL_DLNQ, BBRR4_PP_NOPELL_DFLT,
BBRR4_PP_NOPELL_N, BBRR4_PP_PELL_DISCHARGE, BBRR4_PP_PELL_PAIDINFULL, BBRR4_PP_PELL_MAKEPROG, BBRR4_PP_PELL_NOPROG, BBRR4_PP_PELL_DFR, 
BBRR4_PP_PELL_FBR, BBRR4_PP_PELL_DLNQ, BBRR4_PP_PELL_DFLT, BBRR4_PP_PELL_N, BBRR4_FED_PELL_N, BBRR4_FED_PELL_DFLT, BBRR4_FED_PELL_DLNQ, 
BBRR4_FED_PELL_FBR, BBRR4_FED_PELL_DFR, BBRR4_FED_PELL_NOPROG, BBRR4_FED_PELL_MAKEPROG, BBRR4_FED_PELL_PAIDINFULL, BBRR4_FED_PELL_DISCHARGE, 
BBRR4_FED_NOPELL_N, BBRR4_FED_NOPELL_DFLT, BBRR4_FED_NOPELL_DLNQ, BBRR4_FED_NOPELL_FBR, BBRR4_FED_NOPELL_DFR, BBRR4_FED_NOPELL_NOPROG, 
BBRR4_FED_NOPELL_MAKEPROG, BBRR4_FED_NOPELL_PAIDINFULL, BBRR4_FED_NOPELL_DISCHARGE, BBRR3_PP_NOPELL_DISCHARGE, BBRR3_PP_NOPELL_PAIDINFULL, 
BBRR3_PP_NOPELL_MAKEPROG, BBRR3_PP_NOPELL_NOPROG, BBRR3_PP_NOPELL_DFR, BBRR3_PP_NOPELL_FBR, BBRR3_PP_NOPELL_DLNQ, BBRR3_PP_NOPELL_DFLT, 
BBRR3_PP_NOPELL_N, BBRR3_PP_PELL_DISCHARGE, BBRR3_PP_PELL_PAIDINFULL, BBRR3_PP_PELL_MAKEPROG, BBRR3_PP_PELL_NOPROG, BBRR3_PP_PELL_DFR, 
BBRR3_PP_PELL_FBR, BBRR3_PP_PELL_FBR, BBRR3_PP_PELL_DLNQ, BBRR3_PP_PELL_DFLT, BBRR3_PP_PELL_N, BBRR3_FED_NOPELL_DISCHARGE, 
BBRR3_FED_NOPELL_PAIDINFULL, BBRR3_FED_NOPELL_MAKEPROG, BBRR3_FED_NOPELL_NOPROG, BBRR3_FED_NOPELL_DFR, BBRR3_FED_NOPELL_FBR, 
BBRR3_FED_NOPELL_DLNQ, BBRR3_FED_NOPELL_DFLT, BBRR3_FED_NOPELL_N, BBRR3_FED_PELL_DISCHARGE, BBRR3_FED_PELL_PAIDINFULL, 
BBRR3_FED_PELL_MAKEPROG, BBRR3_FED_PELL_NOPROG, BBRR3_FED_PELL_DFR, BBRR3_FED_PELL_FBR, BBRR3_FED_PELL_DLNQ, BBRR3_FED_PELL_DFLT, 
BBRR3_FED_PELL_N, BBRR2_PP_PELL_N, BBRR2_PP_PELL_DFLT, BBRR2_PP_PELL_DLNQ, BBRR2_PP_PELL_FBR, BBRR2_PP_PELL_DFR, BBRR2_PP_PELL_NOPROG, 
BBRR2_PP_PELL_MAKEPROG, BBRR2_PP_PELL_PAIDINFULL, BBRR2_PP_PELL_DISCHARGE, BBRR2_PP_NOPELL_N, BBRR2_PP_NOPELL_DFLT, BBRR2_PP_NOPELL_DLNQ, 
BBRR2_PP_NOPELL_FBR, BBRR2_PP_NOPELL_DFR, BBRR2_PP_NOPELL_NOPROG, BBRR2_PP_NOPELL_MAKEPROG, BBRR2_PP_NOPELL_PAIDINFULL, 
BBRR2_PP_NOPELL_DISCHARGE, BBRR2_FED_PELL_N, BBRR2_FED_PELL_DFLT, BBRR2_FED_PELL_DLNQ, BBRR2_FED_PELL_FBR, BBRR2_FED_PELL_DFR, 
BBRR2_FED_PELL_NOPROG, BBRR2_FED_PELL_MAKEPROG, BBRR2_FED_PELL_PAIDINFULL, BBRR2_FED_PELL_DISCHARGE, BBRR2_FED_NOPELL_N, BBRR2_FED_NOPELL_DFLT, 
BBRR2_FED_NOPELL_DLNQ, BBRR2_FED_NOPELL_FBR, BBRR2_FED_NOPELL_DFR, BBRR2_FED_NOPELL_NOPROG, BBRR2_FED_NOPELL_MAKEPROG, BBRR2_FED_NOPELL_PAIDINFULL,
BBRR2_FED_NOPELL_DISCHARGE, BBRR1_PP_PELL_N, BBRR1_PP_PELL_DFLT, BBRR1_PP_PELL_DLNQ, BBRR1_PP_PELL_FBR, BBRR1_PP_PELL_DFR, 
BBRR1_PP_PELL_NOPROG, BBRR1_PP_PELL_MAKEPROG, BBRR1_PP_PELL_PAIDINFULL, BBRR1_PP_PELL_DISCHARGE, BBRR1_PP_NOPELL_N, BBRR1_PP_NOPELL_DFLT, 
BBRR1_PP_NOPELL_DLNQ, BBRR1_PP_NOPELL_FBR, BBRR1_PP_NOPELL_DFR, BBRR1_PP_NOPELL_NOPROG, BBRR1_PP_NOPELL_MAKEPROG, BBRR1_PP_NOPELL_PAIDINFULL, 
BBRR1_PP_NOPELL_DISCHARGE, BBRR1_FED_PELL_N, BBRR1_FED_PELL_DFLT, BBRR1_FED_PELL_DLNQ, BBRR1_FED_PELL_FBR, BBRR1_FED_PELL_DFR, 
BBRR1_FED_PELL_NOPROG, BBRR1_FED_PELL_MAKEPROG, BBRR1_FED_PELL_PAIDINFULL, BBRR1_FED_PELL_DISCHARGE, BBRR1_FED_NOPELL_N, BBRR1_FED_NOPELL_DFLT, 
BBRR1_FED_NOPELL_DLNQ, BBRR1_FED_NOPELL_FBR, BBRR1_FED_NOPELL_DFR, BBRR1_FED_NOPELL_NOPROG, BBRR1_FED_NOPELL_MAKEPROG, BBRR1_FED_NOPELL_PAIDINFULL, 
BBRR1_FED_NOPELL_DISCHARGE, D150_L4_PELL_POOLED,	C150_L4_PELL_POOLED	D150_4_PELL_POOLED,	C150_4_PELL_POOLED,	C150_L4_PELL_POOLED_SUPP,	
C150_4_PELL_POOLED_SUPP,	POOLYRS150_PELL	OMENRYP_PELL_ALL,	OMENRAP_PELL_ALL, OMAWDP8_PELL_ALL, OMENRUP_PELL_ALL,	OMENRYP_PELL_FIRSTTIME,	
OMENRAP_PELL_FIRSTTIME,	OMAWDP8_PELL_FIRSTTIME,	OMENRUP_PELL_FIRSTTIME,	OMENRYP_PELL_NOTFIRSTTIME,	OMENRAP_PELL_NOTFIRSTTIME,	
OMAWDP8_PELL_NOTFIRSTTIME,	OMENRUP_PELL_NOTFIRSTTIME, OMENRYP_PELL_FULLTIME,	OMENRAP_PELL_FULLTIME,	OMAWDP8_PELL_FULLTIME,	
OMENRUP_PELL_FULLTIME,	OMENRYP_PELL_PARTTIME,	OMENRAP_PELL_PARTTIME,	OMAWDP8_PELL_PARTTIME	OMENRUP_PELL_PARTTIME,	OMACHT8_PELL_FTFT,
OMAWDP8_PELL_FTFT,	OMENRYP8_PELL_FTFT,	OMENRAP8_PELL_FTFT,	OMENRUP8_PELL_FTFT,	OMACHT8_PELL_PTFT,	OMAWDP8_PELL_PTFT,	
OMENRYP8_PELL_PTFT,	OMENRAP8_PELL_PTFT,	OMENRUP8_PELL_PTFT, OMACHT8_PELL_FTNFT,	OMAWDP8_PELL_FTNFT,	OMENRYP8_PELL_FTNFT,	
OMENRAP8_PELL_FTNFT,	OMENRUP8_PELL_FTNFT,	OMACHT8_PELL_PTNFT,	OMAWDP8_PELL_PTNFT,	OMENRYP8_PELL_PTNFT,	OMENRAP8_PELL_PTNFT,	
OMENRUP8_PELL_PTNFT, OMACHT8_PELL_FTFT_POOLED	OMACHT8_PELL_PTFT_POOLED,	OMACHT8_PELL_FTNFT_POOLED	OMACHT8_PELL_PTNFT_POOLED,	
OMAWDP8_PELL_FTFT_POOLED,	OMENRYP8_PELL_FTFT_POOLED,	OMENRAP8_PELL_FTFT_POOLED,	OMENRUP8_PELL_FTFT_POOLED,	OMAWDP8_PELL_PTFT_POOLED,	
OMENRYP8_PELL_PTFT_POOLED, OMENRAP8_PELL_PTFT_POOLED,	OMENRUP8_PELL_PTFT_POOLED,	OMAWDP8_PELL_FTNFT_POOLED,	OMENRYP8_PELL_FTNFT_POOLED,	
OMENRAP8_PELL_FTNFT_POOLED,	OMENRUP8_PELL_FTNFT_POOLED,	OMAWDP8_PELL_PTNFT_POOLED,	OMENRYP8_PELL_PTNFT_POOLED,	OMENRAP8_PELL_PTNFT_POOLED,
OMENRUP8_PELL_PTNFT_POOLED, OMENRYP_PELL_ALL_POOLED	OMENRAP_PELL_ALL_POOLED,	OMAWDP8_PELL_ALL_POOLED,	OMENRUP_PELL_ALL_POOLED,	
OMENRYP_PELL_FTT_POOLED,	OMENRAP_PELL_FTT_POOLED,	OMAWDP8_PELL_FTT_POOLED,	OMENRUP_PELL_FTT_POOLED	OMENRYP_PELL_NFT_POOLED,	
OMENRAP_PELL_NFT_POOLED, OMAWDP8_PELL_NFT_POOLED,	OMENRUP_PELL_NFT_POOLED,	OMENRYP_PELL_FT_POOLED,	OMENRAP_PELL_FT_POOLED,	
OMAWDP8_PELL_FT_POOLED,	OMENRUP_PELL_FT_POOLED,	OMENRYP_PELL_PT_POOLED,	OMENRAP_PELL_PT_POOLED,	OMAWDP8_PELL_PT_POOLED,	
OMENRUP_PELL_PT_POOLED, POOLYRSOM_PELL_FTFT,	POOLYRSOM_PELL_PTFT,	POOLYRSOM_PELL_FTNFT,	POOLYRSOM_PELL_PTNFT,	POOLYRSOM_PELL_ALL,	
POOLYRSOM_PELL_FIRSTTIME,	POOLYRSOM_PELL_NOTFIRSTTIME,	POOLYRSOM_PELL_FULLTIME,	POOLYRSOM_PELL_PARTTIME, OMAWDP8_PELL_FTFT_POOLED_SUPP,	
OMENRYP8_PELL_FTFT_POOLED_SUPP,	OMENRAP8_PELL_FTFT_POOLED_SUPP,	OMENRUP8_PELL_FTFT_POOLED_SUPP,	OMAWDP8_PELL_PTFT_POOLED_SUPP,	
OMENRYP8_PELL_PTFT_POOLED_SUPP,	OMENRAP8_PELL_PTFT_POOLED_SUPP,	OMENRUP8_PELL_PTFT_POOLED_SUPP,	OMAWDP8_PELL_FTNFT_POOLED_SUPP, 
OMENRYP8_PELL_FTNFT_POOLED_SUPP,	OMENRAP8_PELL_FTNFT_POOLED_SUPP,	OMENRUP8_PELL_FTNFT_POOLED_SUPP,	OMAWDP8_PELL_PTNFT_POOLED_SUPP,	
OMENRYP8_PELL_PTNFT_POOLED_SUPP,	OMENRAP8_PELL_PTNFT_POOLED_SUPP,	OMENRUP8_PELL_PTNFT_POOLED_SUPP,	OMENRYP_PELL_ALL_POOLED_SUPP,	
OMENRAP_PELL_ALL_POOLED_SUPP, OMAWDP8_PELL_ALL_POOLED_SUPP,	OMENRUP_PELL_ALL_POOLED_SUPP,	OMENRYP_PELL_FTT_POOLED_SUPP,	
OMENRAP_PELL_FTT_POOLED_SUPP,	OMAWDP8_PELL_FTT_POOLED_SUPP,	OMENRUP_PELL_FTT_POOLED_SUPP,	OMENRYP_PELL_NFT_POOLED_SUPP,	
OMENRAP_PELL_NFT_POOLED_SUPP,	OMAWDP8_PELL_NFT_POOLED_SUPP,	OMENRUP_PELL_NFT_POOLED_SUPP,	OMENRYP_PELL_FT_POOLED_SUPP,	
OMENRAP_PELL_FT_POOLED_SUPP,	OMAWDP8_PELL_FT_POOLED_SUPP,	OMENRUP_PELL_FT_POOLED_SUPP,	OMENRYP_PELL_PT_POOLED_SUPP,	
OMENRAP_PELL_PT_POOLED_SUPP,	OMAWDP8_PELL_PT_POOLED_SUPP,	OMENRUP_PELL_PT_POOLED_SUPP, PLUS_DEBT_INST_PELL_N,	PLUS_DEBT_INST_PELL_MD,	
PLUS_DEBT_ALL_PELL_N,	PLUS_DEBT_ALL_PELL_MD,	PLUS_DEBT_INST_NOPELL_N,	PLUS_DEBT_INST_NOPELL_MD,	PLUS_DEBT_ALL_NOPELL_N,	
PLUS_DEBT_ALL_NOPELL_MD, C150_4_PELL,	D150_4_PELL	C150_L4_PELL,	D150_L4_PELL,	C150_4_LOANNOPELL,	D150_4_LOANNOPELL,	C150_L4_LOANNOPELL,	
D150_L4_LOANNOPELL,	C150_4_NOLOANNOPELL,	D150_4_NOLOANNOPELL,	C150_L4_NOLOANNOPELL,	D150_L4_NOLOANNOPELL, PELL_RPY_3YR_RT_SUPP,	
NOPELL_RPY_3YR_RT_SUPP, PELL_EVER, PELL_RPY_7YR_N,	NOPELL_RPY_7YR_N, PELL_RPY_5YR_N,	NOPELL_RPY_5YR_N, PELL_RPY_3YR_N,	NOPELL_RPY_3YR_N,
PELL_RPY_1YR_N,	NOPELL_RPY_1YR_N, PELL_DEBT_N,	NOPELL_DEBT_N, PELL_DEBT_MDN,	NOPELL_DEBT_MDN, PELL_YR6_N,	NOPELL_YR6_N, PELL_YR4_N,	
NOPELL_YR4_N, PELL_YR3_N,	NOPELL_YR3_N, PELL_YR2_N,	NOPELL_YR2_N, PELL_RPY_7YR_RT,	NOPELL_RPY_7YR_RT, PELL_RPY_5YR_RT,	NOPELL_RPY_5YR_RT,
PELL_RPY_3YR_RT,	NOPELL_RPY_3YR_RT, PELL_RPY_1YR_RT,	NOPELL_RPY_1YR_RT.


While it may be interesting to look at Pell Grant data, I will not be looking at it for this project, and there are many columns here that 
help me reduce the size of the data file. I want to look specifically at overall costs, since Pell Grants do not apply for all students.

I also deleted the following columns: (columns regarding Title IV students) NUM4_PUB,	NUM4_PRIV,	NUM4_PROG,	NUM4_OTHER,	NUM41_PUB,	
NUM42_PUB,	NUM43_PUB,	NUM44_PUB,	NUM45_PUB, NUM41_PRIV,	NUM42_PRIV,	NUM43_PRIV,	NUM44_PRIV,	NUM45_PRIV,	NUM41_PROG,	NUM42_PROG,	
NUM43_PROG, NUM44_PROG,	NUM45_PROG,	NUM41_OTHER,	NUM42_OTHER,	NUM43_OTHER,	NUM44_OTHER,	NUM45_OTHER. 






